name: Welcome message Workflow

on: [push]

jobs:
   job1-message-Display:
     runs-on: ubuntu-latest
     steps:
        - name: Checking out Current Repository
          uses: actions/checkout@v2

        - name: Configure Runner OS with Python
          uses: actions/setup-python@v4
          with:
             python-version: '3.10'

        -run: python BuildingProject.py   

        -run: ls         